### ISSUE TITLE
Typing Error

### ISSUE THREAD

**Issue by AdrianBories** [asbl/miniworldmaker#9]
In appearences/appearence.py l. 379 "set_image" der Klasse "Appearence":

```
def set_image(self, value):
  if 0 <= value < len(self.images_list) - 1:  # <---- Dort
    self.image_index = value
    self.dirty = 1
    self.parent.dirty = 1
    self._reload_all()
    self.update()
    return True
  else:
    return False
```

Der Index "value" auf welchen in der Liste zugegriffen werden soll darf < len(Liste) sein,
nicht nur < len(Liste) - 1, da man so nicht auf den letzten Index zugreifen kann.

**Comment by asbl** [comment]
Thx. 

Bug wurde in v.1.1 gefixed.

**Comment by asbl** [comment]
closed
